### ISSUE TITLE
oRA3 -missing enchant count with non-beneficial raiding/dg group enchants

### ISSUE THREAD

**Issue by Glowsome** [BigWigsMods/oRA3#100]
## Describe the problem
oRA3  displays in gear-check missing enchants for raiders/groups that do not contribute to raid-/group performance. ( ie. herbalism enchant on hands to herb faster, fall-dmg reducement on feet of leather wearers ( like a healer monk))
This is great for open-world, but these are not the parameters a raid/dg group is looking for (unless you want your raiders to pluck herbs in a raid-instance)

### What steps will reproduce the problem?
This is default behaviour - the addon checks enchantable gearslots, and lists (+1) if an enchant is not present on this slot.
However it does not take into concideration the effectiveness of a/the missing enchant.

1.  Assemble a raid-group in my case incluse a MW monk not having feet enchanted - look at gear-check - observe missing enchants column (detected as 1 missing)
2. action to make Ora 'see' it as enchanted is to let the monk enchant feet with fall-dmg reduction enchant which is useless in regards of raid/dungeon performance.

### Suggestion(s) to solve it.
Let the addon not only look at the possibility of a slot for enchant, but scan the char and identify the enchant ID and compare it to a list of non-raid-beneficial ones and do not list the slot as unenchanted when its in there.

### What version of the addon are you using? (Stating 'latest' is not useful)
v9.0.13

**Comment by funkydude** [comment]
This is incorrect, it is coded to target specific slots based on your spec. However it seems all 3 monk specs are set to the feet slot.
