### ISSUE TITLE
Invite guild button lua errors

### ISSUE THREAD

**Issue by Vladinator89** [BigWigsMods/oRA3#103]
## Describe the problem
Clicking the invite guild button, potentially other buttons might also, doesn't work and casts a lua error.

### What steps will reproduce the problem?

1.  Open oRA2
2.  Go to Invite
3.  Click Invite guild

### Consider attaching a screenshot below to help describe your issue (Attach directly, do not link to other websites)
![image](https://user-images.githubusercontent.com/8304135/112675704-c7375500-8e67-11eb-92b2-e41c7a7cf856.png)

### What version of the addon are you using? (Stating 'latest' is not useful)
v9.0.16

### Do you have an error log of what happened?
    1x oRA3\modules\Invite-Invite.lua:123: attempt to index global 'MAX_PLAYER_LEVEL_TABLE' (a nil value)
    [string "@oRA3\modules\Invite-Invite.lua"]:123: in function <oRA3\modules\Invite.lua:120>

### Any additional information? (example: WoW language if not English)
Nothing relevant that I can think of.

**Comment by Veyska** [comment]
I kept meaning to post about this and forgetting to, oops.  Anyhow, I'd run across a similar error in a completely different mod and the same fix seems to work here.

Current line 123 is:
```local maxLevel = MAX_PLAYER_LEVEL_TABLE[GetExpansionLevel()]```

Fixed line 123 is:
```local maxLevel = GetMaxLevelForLatestExpansion()```

**Comment by nebularg** [comment]
thanks
