### ISSUE TITLE
Vantas Runes for Sanctum of Domination not supported.

### ISSUE THREAD

**Issue by fraerie** [BigWigsMods/oRA3#106]
### What steps will reproduce the problem?

1.  Consumable Check
2.  Not displaying Vantus Rune status for Sanctum of Domination bosses
3.  

### What version of the addon are you using? (Stating 'latest' is not useful)
9.1.0

### Do you have an error log of what happened?
No screenshot or error log, but have looked in the Consumables file and there's no listing for it.

**Comment by axelkic** [comment]
I see the vantus runes in the code, this might be stale and should be closed
