### ISSUE TITLE
Does not support new "Eternal Augment Rune"

### ISSUE THREAD

**Issue by Luckrider** [BigWigsMods/oRA3#108]
## Describe the problem
the Exalted Rep item "Eternal Augment Rune" does not count as a "rune" for buff checks

### What steps will reproduce the problem?

1.  Use Eternal Augment Rune.
2.  Be present for ready check / buff check.
3.  Get yelled at for not having rune.

### Consider attaching a screenshot below to help describe your issue (Attach directly, do not link to other websites)
N/A

### What version of the addon are you using? (Stating 'latest' is not useful)
v9.2.0 (2022-02-23)

### Do you have an error log of what happened?
N/A

### Any additional information? (example: WoW language if not English)
N/A

**Comment by TreizeEU** [comment]
Hi.

I just saw this post, while trying to fix the missing Vantus Runes for Sepulcher.

If you open the file "Consumables.lua" under AddOns/oRA3/Modules and scroll down to line 93 and copy paste the below line, it should work.

		367405, -- Eternal Augmentation


So that it looks like this:


```
local getRune
do
	local runes = {
		270058, -- Battle-Scarred Augmentation
		347901, -- Veiled Augmentation
		367405, -- Eternal Augmentation
	}

	function getRune(player)
		local _, _, id = module:UnitBuffByIDs(player, runes)
		if id then
			return id
		end
		return false
	end
end
```


I hope this helps?
