### ISSUE TITLE
Cross faction autoinvite not working.

### ISSUE THREAD

**Issue by greenstones** [BigWigsMods/oRA3#113]
## Describe the problem
If you are in a raid and are alliance or horde - your auto invite does not pick up the opposite faction even if they are your battle/net friend.  Tested between three different toons on US Hyjal / Malfurion / Stormrage servers.   

### What steps will reproduce the problem?

1.  Have two people sign on to a horde and alliance character and add each other to battle.net id friends.
2.  Set the autoinvite word (invite)
3.  Try to whisper the friend through the list and invite will fail, only works properly if on same faction.

### Consider attaching a screenshot below to help describe your issue (Attach directly, do not link to other websites)
Sorry no screenshot available

### What version of the addon are you using? (Stating 'latest' is not useful)
Ora3 v9.2.1

### Do you have an error log of what happened?
No error pops up just does not work.

**Comment by greenstones** [comment]
Think I found the line to change: LINE 215
if info.clientProgram == BNET_CLIENT_WOW and info.wowProjectID == WOW_PROJECT_MAINLINE and info.factionName == playerFaction and info.realmID > 0 then

Remove the "and info.factionName == playerFaction"

if info.clientProgram == BNET_CLIENT_WOW and info.wowProjectID == WOW_PROJECT_MAINLINE and info.realmID > 0 then

**Comment by greenstones** [comment]
Above change seems to work.

**Comment by nebularg** [comment]
Should be fixed with https://github.com/BigWigsMods/oRA3/commit/1c487d6be236e00a89814584c4a7f8d55dd2c387, but let me know there is still a problem
