### ISSUE TITLE
Dragonflight Beta: Can't open Ora3

### ISSUE THREAD

**Issue by greenstones** [BigWigsMods/oRA3#115]
Soon as you hi the Raid tab, following error pops up.
This is in the most current Beta.,

Message: Interface/AddOns/oRA3/oRA3.lua:757: CreateFrame(): Couldn't find inherited node "CharacterFrameTabButtonTemplate"
Time: Fri Oct  7 19:54:42 2022
Count: 1
Stack: Interface/AddOns/oRA3/oRA3.lua:757: CreateFrame(): Couldn't find inherited node "CharacterFrameTabButtonTemplate"
[string "=[C]"]: in function `CreateFrame'
[string "@Interface/AddOns/oRA3/oRA3.lua"]:757: in function <Interface/AddOns/oRA3/oRA3.lua:632>
[string "@Interface/AddOns/oRA3/oRA3.lua"]:882: in function `ShowUIPanel'
[string "@Interface/AddOns/oRA3/oRA3.lua"]:307: in function <Interface/AddOns/oRA3/oRA3.lua:305>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `SetParent'
[string "@Interface/FrameXML/RaidFrame.lua"]:295: in function `ClaimRaidFrame'
[string "@Interface/FrameXML/FriendsFrame.lua"]:390: in function `FriendsFrame_Update'
[string "@Interface/FrameXML/FriendsFrame.lua"]:345: in function `FriendsFrame_OnShow'
[string "@Interface/FrameXML/FriendsFrame.lua"]:465: in function <Interface/FrameXML/FriendsFrame.lua:463>

Locals: (*temporary) = "Button"
(*temporary) = "oRA3FrameTab1"
(*temporary) = oRA3Frame {
 0 = <userdata>
 drag = Frame {
 }
 title = FontString {
 }
}
(*temporary) = "CharacterFrameTabButtonTemplate"

If you type /ora3 the addon options show up however there is an error in the Alerts section:

Message: Interface/SharedXML/SharedUIPanelTemplates.lua:503: attempt to index field 'Text' (a nil value)
Time: Fri Oct  7 19:59:51 2022
Count: 3
Stack: Interface/SharedXML/SharedUIPanelTemplates.lua:503: attempt to index field 'Text' (a nil value)
[string "@Interface/SharedXML/SharedUIPanelTemplates.lua"]:503: in function `PanelTemplates_TabResize'
[string "*UnknownFile:78_OnShow"]:1: in function <[string "*UnknownFile:78_OnShow"]:1>
[string "=[C]"]: ?
[string "@Interface/AddOns/oRA3/libs/AceGUI-3.0/widgets/AceGUIContainer-TabGroup.lua"]:106: in function `CreateTab'
[string "@Interface/AddOns/oRA3/libs/AceGUI-3.0/widgets/AceGUIContainer-TabGroup.lua"]:183: in function `BuildTabs'
[string "@Interface/AddOns/oRA3/libs/AceGUI-3.0/widgets/AceGUIContainer-TabGroup.lua"]:162: in function `SetTabs'
[string "@Interface/AddOns/oRA3/libs/AceConfigDialog-3.0/AceConfigDialog-3.0.lua"]:1671: in function `FeedGroup'
[string "@Interface/AddOns/oRA3/libs/AceConfigDialog-3.0/AceConfigDialog-3.0.lua"]:1566: in function <...RA3/libs/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:1550>
[string "=[C]"]: ?
[string "@Interface/AddOns/oRA3/libs/AceGUI-3.0/AceGUI-3.0.lua"]:72: in function <Interface/AddOns/oRA3/libs/AceGUI-3.0/AceGUI-3.0.lua:70>
[string "@Interface/AddOns/oRA3/libs/AceGUI-3.0/AceGUI-3.0.lua"]:306: in function `Fire'
[string "@Interface/AddOns/oRA3/libs/AceGUI-3.0/widgets/AceGUIContainer-TreeGroup.lua"]:512: in function `SetSelected'
[string "@Interface/AddOns/oRA3/libs/AceGUI-3.0/widgets/AceGUIContainer-TreeGroup.lua"]:189: in function <...ibs/AceGUI-3.0/widgets/AceGUIContainer-TreeGroup.lua:185>

Locals: tab = AceGUITabGroup3Tab1 {
 0 = <userdata>
 selectedTextY = -2
 deselectedTextY = -3
}
padding = 0
absoluteSize = nil
minWidth = nil
maxWidth = nil
absoluteTextSize = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'Text' (a nil value)"
TAB_SIDES_PADDING = 20

Message: Interface/SharedXML/SharedUIPanelTemplates.lua:501: attempt to index field 'Text' (a nil value)
Time: Fri Oct  7 19:59:51 2022
Count: 3
Stack: Interface/SharedXML/SharedUIPanelTemplates.lua:501: attempt to index field 'Text' (a nil value)
[string "@Interface/SharedXML/SharedUIPanelTemplates.lua"]:501: in function `PanelTemplates_TabResize'
[string "@Interface/AddOns/oRA3/libs/AceGUI-3.0/widgets/AceGUIContainer-TabGroup.lua"]:42: in function `SetText'
[string "@Interface/AddOns/oRA3/libs/AceGUI-3.0/widgets/AceGUIContainer-TabGroup.lua"]:188: in function `BuildTabs'
[string "@Interface/AddOns/oRA3/libs/AceGUI-3.0/widgets/AceGUIContainer-TabGroup.lua"]:162: in function `SetTabs'
[string "@Interface/AddOns/oRA3/libs/AceConfigDialog-3.0/AceConfigDialog-3.0.lua"]:1671: in function `FeedGroup'
[string "@Interface/AddOns/oRA3/libs/AceConfigDialog-3.0/AceConfigDialog-3.0.lua"]:1566: in function <...RA3/libs/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:1550>
[string "=[C]"]: ?
[string "@Interface/AddOns/oRA3/libs/AceGUI-3.0/AceGUI-3.0.lua"]:72: in function <Interface/AddOns/oRA3/libs/AceGUI-3.0/AceGUI-3.0.lua:70>
[string "@Interface/AddOns/oRA3/libs/AceGUI-3.0/AceGUI-3.0.lua"]:306: in function `Fire'
[string "@Interface/AddOns/oRA3/libs/AceGUI-3.0/widgets/AceGUIContainer-TreeGroup.lua"]:512: in function `SetSelected'
[string "@Interface/AddOns/oRA3/libs/AceGUI-3.0/widgets/AceGUIContainer-TreeGroup.lua"]:189: in function <...ibs/AceGUI-3.0/widgets/AceGUIContainer-TreeGroup.lua:185>

Locals: <none>

**Comment by funkydude** [comment]
This should be fixed in newest release.
