### ISSUE TITLE
Ora3 tosses an error when trying to sort in its buff section.

### ISSUE THREAD

**Issue by greenstones** [BigWigsMods/oRA3#116]
## Describe the problem
Ora3 tosses an error when trying to sort in its buff section.

### What steps will reproduce the problem?

1.  Join a raid,
2.  Open the Ora3 panel, go to checks buffs.
3.  Click on top label to sort by food or whatever.

### Consider attaching a screenshot below to help describe your issue (Attach directly, do not link to other websites)
![image](https://user-images.githubusercontent.com/42426983/198866790-1607152a-e895-47a1-99ad-26076352b6a7.png)

### What version of the addon are you using? (Stating 'latest' is not useful)
Ora3-v9.2.1.zip

### Do you have an error log of what happened?
Pictured in the screen.

### Any additional information? (example: WoW language if not English)
Don't have a text version error does not occur when you are solo only in a group.

**Comment by funkydude** [comment]
> Ora3-v9.2.1.zip

This is an old version

**Comment by greenstones** [comment]
Still happening in version 10.0.1



Restarted the game after updating:
If you click on food or flasks it gives an error.

![image](https://user-images.githubusercontent.com/42426983/198936214-b7be4e71-0e9b-4d4a-afb4-e7cfad50df64.png)
