### ISSUE TITLE
Disband Group error ver 10.0.1

### ISSUE THREAD

**Issue by greenstones** [BigWigsMods/oRA3#117]
## Describe the problem
![image](https://user-images.githubusercontent.com/42426983/198931014-178bb297-8150-4f20-9f4a-8fe66e63db42.png)

Message: bad argument #2 to '?' (Usage: C_Timer.After(seconds, callback))
Time: Mon Oct 31 00:25:56 2022
Count: 6
Stack: bad argument #2 to '?' (Usage: C_Timer.After(seconds, callback))

Locals: 

### What steps will reproduce the problem?

1.  Be in a raid group
2.  Open ORAa3
3.  Try to Disband group

**Comment by funkydude** [comment]
Thanks for reporting! Will be fixed next release.
