### ISSUE TITLE
Battle Rez monitor does not stay up.

### ISSUE THREAD

**Issue by greenstones** [BigWigsMods/oRA3#118]
## Describe the problem
Battle rez monitor does not stay/show up even if you have always show on, you are forced to hit toggle to make it come up.

No errors.

V10.0.2

![image](https://user-images.githubusercontent.com/42426983/199520447-3f0779ee-e30a-4246-8e44-ae4525db2f63.png)

After I hit Toggle:

![image](https://user-images.githubusercontent.com/42426983/199520622-62e99a55-4f3c-4e60-916c-45f9c48c661d.png)

**Comment by greenstones** [comment]
In raid it doesn't show up:

![image](https://user-images.githubusercontent.com/42426983/199524333-5ce4f603-eb8a-4a8f-9e4c-94b313ada540.png)

**Comment by funkydude** [comment]
Working as intended. It's designed to show up when you're in an area that uses the limited battle res system (actual raid instances).
