### ISSUE TITLE
Clicking on Flasks in the buff window tosses an error.

### ISSUE THREAD

**Issue by greenstones** [BigWigsMods/oRA3#119]
## Describe the problem
When you click on"FLASK" in the buffs window - and sort it tries to sort it gives an error.

### What steps will reproduce the problem?

1.  Join a raid.
2.  Open the ora3 panel click on Checks tab, buffs button.
3.  Click on Flasks heading, to sort, and it will toss an error.

### Consider attaching a screenshot below to help describe your issue (Attach directly, do not link to other websites)
![image](https://user-images.githubusercontent.com/42426983/199526970-a749135f-3f71-40a4-a9e7-45e918bae0b1.png)

### What version of the addon are you using? (Stating 'latest' is not useful)
V 10.0.2

### Do you have an error log of what happened?
Message: Interface/AddOns/oRA3/oRA3.lua:1177: attempt to compare number with string
Time: Wed Nov  2 11:11:17 2022
Count: 12
Stack: Interface/AddOns/oRA3/oRA3.lua:1177: attempt to compare number with string

Locals: 

### Any additional information? (example: WoW language if not English)
This is on retail.

**Comment by greenstones** [comment]
https://imgur.com/tQVukM6

**Comment by funkydude** [comment]
![image](https://user-images.githubusercontent.com/16833/201831310-c16792ca-6d3e-481d-883c-9ef275ceb632.png)

@greenstones As you can see above your post, the issue was closed and marked as completed by a linked code change. This change will end up in the next release.

It's ok to not understand how this works since you can just ask, but there's no need to open duplicate issues.

**Comment by greenstones** [comment]
Sorry but there was another release of v10.0.2 and I downloaded it and still was present did not know that you were going to release a 10.0.3 or whatever the version was to fix it.  I use the addon on a regular basis and have reported multiple errors which have not been fixed but the code got updated on curse so you are correct not sure how it works how fast or slow it is, is not easy to determine by someone outside of the process.  Again thank you for updating and the addon.

**Comment by funkydude** [comment]
I don't know what you mean by "another release of v10.0.2" as we don't re-release under the same number.
![image](https://user-images.githubusercontent.com/16833/201834007-9466b1fa-e7f9-4da0-9917-8dc914e21836.png)
This version was released 2 weeks ago.

But you are right in saying the next version will be v10.0.3 and will contain this fix!

**Comment by greenstones** [comment]
Yeah I see that - curseforge seems to show you released a new version 4 hours ago.

![image](https://user-images.githubusercontent.com/42426983/201848322-fddd03a9-400d-42df-9b74-59ac06702860.png)

Thats why there was a confusion regarding it.  I am using their site and whenever it shows a update I think its a change the addon authors did.  Not sure why it does that though if its not a new release it shouldn't say its been updated.  Again thanks for listening and for the addon!
