### ISSUE TITLE
Lua Error on Entering Raid/Ressurrect in Raid

### ISSUE THREAD

**Issue by FireAllianceNX** [BigWigsMods/oRA3#124]
## Describe the problem
Lua Error

### What steps will reproduce the problem?

1.  Entering raid or rezzing in raid or ready checks
2.  
3.  

### What version of the addon are you using? (Stating 'latest' is not useful)
10.0.3

### Do you have an error log of what happened?
```
59x oRA3/modules/Cooldowns/Cooldowns.lua:198: bad argument #1 to '(for generator)' (table expected, got nil)
[string "=[C]"]: in function `(for generator)'
[string "@oRA3/modules/Cooldowns/Cooldowns.lua"]:198: in function <oRA3/modules/Cooldowns/Cooldowns.lua:196>
[string "@oRA3/modules/Cooldowns/Cooldowns.lua"]:1303: in function `?'
[string "@Masque/Libs/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:114: in function <...que/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:114>
[string "=[C]"]: ?
[string "@Masque/Libs/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:24: in function <...que/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:20>
[string "@Masque/Libs/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:59: in function `Fire'
[string "@oRA3/oRA3.lua"]:451: in function `?'
[string "@Masque/Libs/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:114: in function <...que/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:114>
[string "=[C]"]: ?
[string "@Masque/Libs/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:24: in function <...que/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:20>
[string "@Masque/Libs/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:59: in function `Fire'
[string "@oRA3/libs/LibGroupInSpecT-1.1-92/LibGroupInSpecT-1.1.lua"]:864: in function `eventhandler'
[string "@oRA3/libs/LibGroupInSpecT-1.1-92/LibGroupInSpecT-1.1.lua"]:129: in function <...RA3/libs/LibGroupInSpecT-1.1/LibGroupInSpecT-1.1.lua:127>
```

**Comment by madar2252** [comment]
Getting the same when I am in party, and the battle res monitor is out.

**Comment by MystbornGames** [comment]
Same issue, I think. Happened when I joined a world boss raid. Version 10.0.2

13x oRA3/modules/Cooldowns/Cooldowns.lua:198: bad argument #1 to '(for generator)' (table expected, got nil)
[string "=[C]"]: in function `(for generator)'
[string "@oRA3/modules/Cooldowns/Cooldowns.lua"]:198: in function <oRA3/modules/Cooldowns/Cooldowns.lua:196>
[string "@oRA3/modules/Cooldowns/Cooldowns.lua"]:1303: in function `?'
[string "@AllTheThings/lib/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:119: in function <...ings/lib/CallbackHandler-1.0/CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@AllTheThings/lib/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:29: in function <...ings/lib/CallbackHandler-1.0/CallbackHandler-1.0.lua:25>
[string "@AllTheThings/lib/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:64: in function `Fire'
[string "@oRA3/oRA3.lua"]:451: in function `?'
[string "@AllTheThings/lib/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:119: in function <...ings/lib/CallbackHandler-1.0/CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@AllTheThings/lib/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:29: in function <...ings/lib/CallbackHandler-1.0/CallbackHandler-1.0.lua:25>
[string "@AllTheThings/lib/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:64: in function `Fire'
[string "@oRA3/libs/LibGroupInSpecT-1.1-92/LibGroupInSpecT-1.1.lua"]:864: in function `eventhandler'
[string "@oRA3/libs/LibGroupInSpecT-1.1-92/LibGroupInSpecT-1.1.lua"]:129: in function <...RA3/libs/LibGroupInSpecT-1.1/LibGroupInSpecT-1.1.lua:127>

**Comment by nebularg** [comment]
Fixed with https://github.com/BigWigsMods/oRA3/commit/045abe25c54ece762c6ab025713e22db720540f1
