### ISSUE TITLE
Ora3 tosses error when cooldown monitor is active.

### ISSUE THREAD

**Issue by greenstones** [BigWigsMods/oRA3#125]
## Describe the problem
Tosses an error in raid on retail wow when cooldown monitor is turned on.  
Might be tainted by another addon called ChatCopyPaste will have to test further.

### What steps will reproduce the problem?

1.  Enter a raid of 10+ people
2.  Enable cooldown monitor
3.  Error occurs.

### Consider attaching a screenshot below to help describe your issue (Attach directly, do not link to other websites)
Message: ...nterface/AddOns/oRA3/modules/Cooldowns/Cooldowns.lua:198: bad argument #1 to '(for generator)' (table expected, got nil)
Time: Wed Nov 23 21:22:31 2022
Count: 1
Stack: ...nterface/AddOns/oRA3/modules/Cooldowns/Cooldowns.lua:198: bad argument #1 to '(for generator)' (table expected, got nil)
[string "@Interface/AddOns/ChatCopyPaste/Lib/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:119: in function <...aste/Lib/CallbackHandler-1.0/CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@Interface/AddOns/ChatCopyPaste/Lib/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:29: in function <...aste/Lib/CallbackHandler-1.0/CallbackHandler-1.0.lua:25>
[string "@Interface/AddOns/ChatCopyPaste/Lib/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:64: in function `Fire'
[string "@Interface/AddOns/oRA3/oRA3.lua"]:451: in function `?'
[string "@Interface/AddOns/ChatCopyPaste/Lib/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:119: in function <...aste/Lib/CallbackHandler-1.0/CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@Interface/AddOns/ChatCopyPaste/Lib/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:29: in function <...aste/Lib/CallbackHandler-1.0/CallbackHandler-1.0.lua:25>
[string "@Interface/AddOns/ChatCopyPaste/Lib/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:64: in function `Fire'
[string "@Interface/AddOns/oRA3/libs/LibGroupInSpecT-1.1/LibGroupInSpecT-1.1.lua"]:638: in function `eventhandler'
[string "@Interface/AddOns/oRA3/libs/LibGroupInSpecT-1.1/LibGroupInSpecT-1.1.lua"]:129: in function <...RA3/libs/LibGroupInSpecT-1.1/LibGroupInSpecT-1.1.lua:127>

Locals: <none>

### What version of the addon are you using? (Stating 'latest' is not useful)
Ora3 voRA3-v10.0.3.zip

**Comment by nebularg** [comment]
Fixed with https://github.com/BigWigsMods/oRA3/commit/045abe25c54ece762c6ab025713e22db720540f1
