### ISSUE TITLE
Bug on clicking edit mode as soon as  you get into the game.

### ISSUE THREAD

**Issue by greenstones** [BigWigsMods/oRA3#126]
## Describe the problem
As soon as you log in if you click edit mode there is a chance that ora3 will toss up an error.  Doesn't always happen but I caught it this time when it did a few others in my guild get this often though.

### What steps will reproduce the problem?

1.  Completely log out of the game, then log back in.
2.  Go to edit mode as your first action.
3.  Catch the error.

### Consider attaching a screenshot below to help describe your issue (Attach directly, do not link to other websites)
No screen shot just a copy and paste of the error this time.

### What version of the addon are you using? (Stating 'latest' is not useful)
WOW Retail (Dragonflight) - Ora3-10.0.4.zip

### Do you have an error log of what happened?
Message: [ADDON_ACTION_FORBIDDEN] AddOn 'oRA3' tried to call the protected function 'TargetUnit()'.
Time: Fri Dec  2 13:45:21 2022
Count: 1
Stack: [ADDON_ACTION_FORBIDDEN] AddOn 'oRA3' tried to call the protected function 'TargetUnit()'.
[string "@Interface/FrameXML/EditModeManager.lua"]:1463: in function `OnEditModeEnter'
[string "@Interface/FrameXML/EditModeManager.lua"]:170: in function <Interface/FrameXML/EditModeManager.lua:165>
[string "=[C]"]: in function `EnterEditMode'
[string "@Interface/FrameXML/EditModeManager.lua"]:192: in function <Interface/FrameXML/EditModeManager.lua:190>
[string "=[C]"]: ?
[string "=[C]"]: in function `Show'
[string "@Interface/FrameXML/UIParent.lua"]:2853: in function `SetUIPanel'
[string "@Interface/FrameXML/UIParent.lua"]:2657: in function `ShowUIPanel'
[string "@Interface/FrameXML/UIParent.lua"]:2561: in function <Interface/FrameXML/UIParent.lua:2557>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface/FrameXML/UIParent.lua"]:3159: in function <Interface/FrameXML/UIParent.lua:3138>
[string "=[C]"]: in function `ShowUIPanel'
[string "@Interface/FrameXML/FloatingChatFrame.lua"]:282: in function `func'
[string "@Interface/SharedXML/UIDropDownMenu.lua"]:1007: in function `UIDropDownMenuButton_OnClick'
[string "*UIDropDownMenuTemplates.xml:136_OnClick"]:1: in function <[string "*UIDropDownMenuTemplates.xml:136_OnClick"]:1>

Locals: <none>

**Comment by funkydude** [comment]
Please let us know if this is still happening in patch 10.0.5
