### ISSUE TITLE
Evoker Spells not in list

### ISSUE THREAD

**Issue by Rika-chanXO** [BigWigsMods/oRA3#127]
## Describe the problem
I only use Ora3 to track interrupts in dungeons. Once the evoker got added, I was waiting for an update to be also able to track their interrupts. The evoker got added to the list of classes, but when I select them, the spell list is empty

### What steps will reproduce the problem?

1.  Get Ora3
2.  Go to Cooldowns
3.  Select Evoker

### Consider attaching a screenshot below to help describe your issue (Attach directly, do not link to other websites)
no

### What version of the addon are you using? (Stating 'latest' is not useful)
10.0.5

### Do you have an error log of what happened?
no

### Any additional information? (example: WoW language if not English)
no

**Comment by Redshamrock11** [comment]
Having the same issue as well. Wanted to add the Haste buff ability but none are showing for Evoker. Screenshot attached.
![Screenshot 2023-01-11 135612](https://user-images.githubusercontent.com/122488366/211916216-cce7bbbc-9657-42b7-967a-21b14cfe6aaa.png)
