### ISSUE TITLE
Incorrect buffs showing when doing a ready check

### ISSUE THREAD

**Issue by fraerie** [BigWigsMods/oRA3#131]
## Describe the problem
for buff checking - we are seeing the Int and BattleShout check reversed - it shows int missing if attack power is missing - and if attack power is missing it shows int as missing

### What steps will reproduce the problem?

1.  be in a raid and do a ready check
2.  
3.  

### What version of the addon are you using? (Stating 'latest' is not useful)
ORA3 v10.0.7
Game client 10.0.5.48397

**Comment by nebularg** [comment]
Thanks
