### ISSUE TITLE
10.1.5 - oRA3: Invalid spell id 152262 - Seraphim

### ISSUE THREAD

**Issue by voidzone** [BigWigsMods/oRA3#134]
Seraphim no longer exists in Retail.

**Comment by Robotnik247** [comment]
Go to line 674 in data.lua and omit the line: `[152262] = {45, 40, nil, 15}, -- Seraphim`

**Comment by anarchopunkbarbie** [comment]
This is still throwing an error as of 10.1.7 (51313).
Alliance: Miryam/Amiele/Gnoyou
Horde: Moohammed
