### ISSUE TITLE
LibGroupInSpec

### ISSUE THREAD

**Issue by HDMOVIESOURCE** [BigWigsMods/oRA3#135]
1205x ...RA3/libs/LibGroupInSpecT-1.1-93/LibGroupInSpecT-1.1.lua:883: attempt to index field 'activeEntry' (a nil value)
[string "@oRA3/libs/LibGroupInSpecT-1.1-93/LibGroupInSpecT-1.1.lua"]:883: in function `eventhandler'
[string "@LibGroupInSpecT-1.1-93/LibGroupInSpecT-1.1.lua"]:129: in function <...eLibGroupInSpecT-1.1/LibGroupInSpecT-1.1.lua:127>

Locals:
self = <table> {
 DoPlayerUpdate = <function> defined @oRA3/libs/LibGroupInSpecT-1.1/LibGroupInSpecT-1.1.lua:721
 GetCachedInfo = <function> defined @oRA3/libs/LibGroupInSpecT-1.1/LibGroupInSpecT-1.1.lua:1035
 PLAYER_ENTERING_WORLD = <function> defined @oRA3/libs/LibGroupInSpecT-1.1/LibGroupInSpecT-1.1.lua:682
 BuildInfo = <function> defined @oRA3/libs/LibGroupInSpecT-1.1/LibGroupInSpecT-1.1.lua:549
 GetCachedPvpTalentInfoByID = <function> defined @oRA3/libs/LibGroupInSpecT-1.1/LibGroupInSpecT-1.1.lua:379
 INSPECT_READY = <function> defined @oRA3/libs/LibGroupInSpecT-1.1/LibGroupInSpecT-1.1.lua:652
 Query = <function> defined @oRA3/libs/LibGroupInSpecT-1.1/LibGroupInSpecT-1.1.lua:437
 UpdatePlayerInfo = <function> defined @oRA3/libs/LibGroupInSpecT-1.1/LibGroupInSpecT-1.1.lua:538
 UNIT_LEVEL = <function> defined @oRA3/libs/LibGroupInSpecT-1.1/LibGroupInSpecT-1.1.lua:933
 hooked = true
 UNIT_NAME_UPDATE = <function> defined @oRA3/libs/LibGroupInSpecT-1.1/LibGroupInSpecT-1.1.lua:959
 PLAYER_SPECIALIZATION_CHANGED = <function> defined @oRA3/libs/LibGroupInSpecT-1.1/LibGroupInSpecT-1.1.lua:948
 RegisterCallback = <function> defined @Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:80
 state = <table> {
 }
 GuidToUnit = <function> defined @oRA3/libs/LibGroupInSpecT-1.1/LibGroupInSpecT-1.1.lua:424
 IsInspectQueued = <function> defined @oRA3/libs/LibGroupInSpecT-1.1/LibGroupInSpecT-1.1.lua:1030
 UpdateCommScope = <function> defined @oRA3/libs/LibGroupInSpecT-1.1/LibGroupInSpecT-1.1.lua:803
 cache = <table> {
 }
 PLAYER_LOGIN = <function> defined @oRA3/libs/LibGroupInSpecT-1.1/LibGroupInSpecT-1.1.lua:265
 GROUP_ROSTER_UPDATE = <function> defined @oRA3/libs/LibGroupInSpecT-1.1/LibGroupInSpecT-1.1.lua:694
 commScope = "PARTY"
 Rescan = <function> defined @oRA3/libs/LibGroupInSpecT-1.1/LibGroupInSpecT-1.1.lua:1041
 NotifyInspect = <function> defined @oRA3/libs/LibGroupInSpecT-1.1/LibGroupInSpecT-1.1.lua:156
 QueuedInspections = <function> defined @oRA3/libs/LibGroupInSpecT-1.1/LibGroupInSpecT-1.1.lua:1012
 GroupUnits = <function> defined @oRA3/libs/LibGroupInSpecT-1.1/LibGroupInSpecT-1.1.lua:1084
 UNIT_AURA = <function> defined @oRA3/libs/LibGroupInSpecT-1.1/LibGroupInSpecT-1.1.lua:973
 UnregisterAllCallbacks = <function> defined @Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:164
 inspect_ready_used = true
 static_cache = <table> {
 }
 CacheGameData = <function> defined @oRA3/libs/LibGroupInSpecT-1.1/LibGroupInSpecT-1.1.lua:402
 GetCachedTalentInfo = <function> defined @oRA3/libs/LibGroupInSpecT-1.1/LibGroupInSpecT-1.1.lua:330
 StaleInspections = <function> defined @oRA3/libs/LibGroupInSpecT-1.1/LibGroupInSpecT-1.1.lua:1021
 Refresh = <function> defined @oRA3/libs/LibGroupInSpecT-1.1/LibGroupInSpecT-1.1.lua:457
 UNIT_SPELLCAST_SUCCEEDED = <function> defined @oRA3/libs/LibGroupInSpecT-1.1/LibGroupInSpecT-1.1.lua:1003
 SendLatestSpecData = <function> defined @oRA3/libs/LibGroupInSpecT-1.1/LibGroupInSpecT-1.1.lua:728
 PLAYER_LOGOUT = <function> defined @oRA3/libs/LibGroupInSpecT-1.1/LibGroupInSpecT-1.1.lua:287
 GetCachedTalentInfoByID = <function> defined @oRA3/libs/LibGroupInSpecT-1.1/LibGroupInSpecT-1.1.lua:352
 events = <table> {
 }
 PLAYER_TALENT_UPDATE = <function> defined @oRA3/libs/LibGroupInSpecT-1.1/LibGroupInSpecT-1.1.lua:943
 CHAT_MSG_ADDON = <function> defined @oRA3/libs/LibGroupInSpecT-1.1/LibGroupInSpecT-1.1.lua:821
 frame = LibGroupInSpecT-1.1_Frame {
 }
 ProcessQueues = <function> defined @oRA3/libs/LibGroupInSpecT-1.1/LibGroupInSpecT-1.1.lua:470

**Comment by nebularg** [comment]
Thanks, I updated the lib

**Comment by HDMOVIESOURCE** [comment]
I do appreciate it, thank you.

**Comment by nebularg** [comment]
And now should be included with v10.2.3
