### ISSUE TITLE
Error on loading into the gamae

### ISSUE THREAD

**Issue by tommy610** [BigWigsMods/oRA3#137]
## Describe the problem
Error pops up when loading into the game

### What steps will reproduce the problem?

1.  Loading into the game
2.  
3.  

### What version of the addon are you using? (Stating 'latest' is not useful)
oRA3-v10.2.5

### Do you have an error log of what happened?
5x SharedXML/TableUtil.lua:249: bad argument #1 to 'pairs' (table expected, got nil)
[string "=[C]"]: in function `pairs'
[string "@SharedXML/TableUtil.lua"]:249: in function `MergeTable'
[string "@Blizzard_Deprecated/Deprecated_10_2_5.lua"]:19: in function `GetItemStats'
[string "@oRA3/modules/Gear.lua"]:156: in function `ScanGear'
[string "@oRA3/modules/Gear.lua"]:85: in function `?'
[string "@AllTheThings/lib/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:109: in function <...ings/lib/CallbackHandler-1.0/CallbackHandler-1.0.lua:109>
[string "=[C]"]: ?
[string "@AllTheThings/lib/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...ings/lib/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@AllTheThings/lib/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@oRA3/oRA3.lua"]:459: in function `?'
[string "@AllTheThings/lib/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:109: in function <...ings/lib/CallbackHandler-1.0/CallbackHandler-1.0.lua:109>
[string "=[C]"]: ?
[string "@AllTheThings/lib/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...ings/lib/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@AllTheThings/lib/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@GladiusEx/libs/LibGroupInSpecT-1.1-94/LibGroupInSpecT-1.1.lua"]:673: in function `eventhandler'
[string "@GladiusEx/libs/LibGroupInSpecT-1.1-94/LibGroupInSpecT-1.1.lua"]:131: in function <...sEx/libs/LibGroupInSpecT-1.1/LibGroupInSpecT-1.1.lua:129>

Locals:
(*temporary) = nil
(*temporary) = "table expected, got nil"
 = <function> defined =[C]:-1

**Comment by nebularg** [comment]
Thanks, I hadn't see that, but apparently the API can return nil now
