### ISSUE TITLE
Lua errors on live 11.0.0

### ISSUE THREAD

**Issue by MysticalOS** [BigWigsMods/oRA3#140]
Seeing following error a lot in follower dungeons I'm doing tonight on Prot warrior

16x oRA3/modules/Cooldowns/Cooldowns.lua:150: attempt to index field '?' (a nil value)
[string "@oRA3/modules/Cooldowns/Cooldowns.lua"]:150: in function <oRA3/modules/Cooldowns/Cooldowns.lua:149>
[string "=(tail call)"]: ?
[string "@oRA3/modules/Cooldowns/Cooldowns.lua"]:200: in function <oRA3/modules/Cooldowns/Cooldowns.lua:186>
[string "@oRA3/modules/Cooldowns/Cooldowns.lua"]:215: in function <oRA3/modules/Cooldowns/Cooldowns.lua:211>
[string "@oRA3/modules/Cooldowns/Cooldowns.lua"]:1345: in function `?'
[string "@Ace3/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:109: in function <...Ons/Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:109>
[string "=[C]"]: ?
[string "@Ace3/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...Ons/Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@Ace3/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@oRA3/oRA3.lua"]:451: in function `?'
[string "@Ace3/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:109: in function <...Ons/Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:109>
[string "=[C]"]: ?
[string "@Ace3/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...Ons/Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@Ace3/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@oRA3/libs/LibGroupInSpecT-1.1-95/LibGroupInSpecT-1.1.lua"]:1024: in function `Rescan'
[string "@oRA3/oRA3.lua"]:464: in function `?'
[string "@Ace3/AceTimer-3.0-17/AceTimer-3.0.lua"]:55: in function <Ace3/AceTimer-3.0/AceTimer-3.0.lua:50>

Locals:
self = <table> {
 modules = <table> {
 }
 enabled = true
 defaultModuleState = true
 db = <table> {
 }
 enabledState = true
 orderedModules = <table> {
 }
 classLookup = <table> {
 }
 baseName = "oRA3"
 defaultModuleLibraries = <table> {
 }
 allSpells = <table> {
 }
 moduleName = "Cooldowns"
 name = "oRA3_Cooldowns"
}
guid = "Player-5-0E597C96"
spellId = 152277
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field '?' (a nil value)"
allSpells = <table> {
 199483 = <table> {
 }
 106839 = <table> {
 }
 202425 = <table> {
 }
 198589 = <table> {
 }
 263165 = <table> {
 }
 2050 = <table> {
 }
 246287 = <table> {
 }
 426591 = <table> {
 }
 275699 = <table> {
 }
 20572 = <table> {
 }
 122121 = <table> {
 }
 10326 = <table> {
 }
 1044 = <table> {
 }
 359844 = <table> {
 }
 22842 = <table> {
 }
 390279 = <table> {
 }
 66 = <table> {
 }
 228260 = <table> {
 }
 322507 = <table> {
 }
 207289 = <table> {
 }
 52174 = <table> {
 }
 383121 = <table> {
 }
 102558 = <table> {
 }
 385424 = <table> {
 }
 391054 = <table> {
 }
 58984 = <table> {
 }
 68992 = <table> {
 }
 136 = <table> {
 }
 210873 = <table> {
 }
 271877 = <table> {
 }
 190925 = <table> {
 }
 102560 = <table> {
 }
 20589 = <table> {
 }
 192077 = <table> {
 }
 59752 = <table> {
 }
 207167 = <table> {
 }
 96231 = <table> {
 }
 211004 = <table> {
 }
 34433 = <table> {
 }
 260364 = <table> {
 }
 324312 = <table> {
 }
 196555 = <table> {
 }
 319454 = <table> {
 }
 1122 = <table> {
 }
 279302 = <table> {
 }
 213691 = <table> {
 }
 115989 = <table> {
 }
 385952 = <table> {
 }
 205636 = <table> {
 }
 188501 = <table> {
 }
 305392 = <table> {
 }
 42650 = <table> {
 }
 111898 = <table> {
 }
 321507 = <table> {
 }
 80313 = <table> {
 }
 207684 = <table> {
 }
 88625 = <table> {
 }
 212800 = <table> {
 }
 55342 = <table> {
 }
 1160 = <table> {
 }
 1161 = <table> {
 }
 277778 = <table> {
 }
 264735 = <table> {
 }
 153595 = <table> {
 }
 19647 = <table> {
 }
 29893 = <table> {
 }
 64901 = <table> {
 }
 586 = <table> {
 }
 205385 = <table> {
 }
 22812 = <table> {
 }
 118038 = <table> {
 }
 119381 = <table> {
 }
 374968 = <table> {
 }
 277784 = <table> {
 }
 185311 = <table> {
 }
 3411 = <table> {
 }
 211015 = <table> {
 }
 46584 = <table> {
 }
 381623 = <table> {
 }
 235313 = <table> {
 }
 342240 = <table> {
 }
 212552 = <table> {
 }
 49206 = <table> {
 }
 63560 = <table> {
 }
 101545 = <table> {
 }
 198103 = <table> {
 }
 255647 = <table> {
 }
 50613 = <table> {
 }
 192222 = <table> {
 }
 197721 = <table> {
 }
 272682 = <table> {
 }
 2484 = <table> {
 }
 201430 = <table> {
 }
 33702 = <table> {
 }
 232633 = <table> {
 }
 206931 = <table> {
 }
 633 = <table> {
 }
 48792 = <table> {
 }
 212431 = <table> {
 }
 197214 = <table> {
 }
 196447 = <table> {
 }
 388035 = <table> {
 }
 274738 = <table> {
 }
 642 = <table> {
 }
 255654 = <table> {
 }
 179057 = <table> {
 }
 235450 = <table> {
 }
 274740 = <table> {
 }
 374227 = <table> {
 }
 155145 = <table> {
 }
 20608 = <table> {
 }
 274741 = <table> {
 }
 108199 = <table> {
 }
 169340 = <table> {
 }
 260643 = <table> {
 }
 108839 = <table> {
 }
 114018 = <table> {
 }
 69070 = <table> {
 }
 278326 = <table> {
 }
 259495 = <table> {
 }
 108968 = <table> {
 }
 202719 = <table> {
 }
 205021 = <table> {
 }
 119582 = <table> {
 }
 116705 = <table> {
 }
 205022 = <table> {
 }
 391888 = <table> {
 }
 358385 = <table> {
 }
 57330 = <table> {
 }
 18499 = <table> {
 }
 13877 = <table> {
 }
 214743 = <table> {
 }
 190319 = <table> {
 }
 64843 = <table> {
 }
 205025 = <table> {
 }
 200166 = <table> {
 }
 370665 = <table> {
 }
 64044 = <table> {
 }
 200806 = <table> {
 }
 97462 = <table> {
 }
 5484 = <table> {
 }
 373481 = <table> {
 }
 32182 = <table> {
 }
 61391 = <table> {
 }
 53271 = <table> {
 }
 20066 = <table> {
 }
 43265 = <table> {
 }
 21169 = <table> {
 }
 698 = <table> {
 }
 122783 = <table> {
 }
 115750 = <table> {
 }
 196718 = <table> {
 }
 252216 = <table> {
 }
 386276 = <table> {
 }
 382440 = <table> {
 }
 256948 = <table> {
 }
 86659 = <table> {
 }
 31687 = <table> {
 }
 325153 = <table> {
 }
 392160 = <table> {
 }
 153626

**Comment by nebularg** [comment]
I completely forgot to update the cooldown data x.x I'll try to get that done in the next few days
