### ISSUE TITLE
'Error MEssage when I log in

### ISSUE THREAD

**Issue by Pantasaron** [BigWigsMods/oRA3#146]
When I login in, all other addons except Ora3, Bugsack and Buggrabber enabled, I get following error:

31x bad argument #1 to '?' (Usage: local definitionInfo = C_Traits.GetDefinitionInfo(definitionID))
[string "=[C]"]: in function `GetDefinitionInfo'
[string "@oRA3/libs/LibGroupInSpecT-1.1-95/LibGroupInSpecT-1.1.lua"]:345: in function `GetCachedTalentInfoByID'
[string "@oRA3/libs/LibGroupInSpecT-1.1-95/LibGroupInSpecT-1.1.lua"]:599: in function `BuildInfo'
[string "@oRA3/libs/LibGroupInSpecT-1.1-95/LibGroupInSpecT-1.1.lua"]:424: in function `Query'
[string "@oRA3/libs/LibGroupInSpecT-1.1-95/LibGroupInSpecT-1.1.lua"]:705: in function `DoPlayerUpdate'
[string "@oRA3/libs/LibGroupInSpecT-1.1-95/LibGroupInSpecT-1.1.lua"]:909: in function `eventhandler'
[string "@oRA3/libs/LibGroupInSpecT-1.1-95/LibGroupInSpecT-1.1.lua"]:131: in function <...RA3/libs/LibGroupInSpecT-1.1/LibGroupInSpecT-1.1.lua:129>

Locals:
(*temporary) = "bad argument #1 to '?' (Usage: local definitionInfo = C_Traits.GetDefinitionInfo(definitionID))"

WoW-Client: German - Early Access of TWW

**Comment by nebularg** [comment]
Latest release should have an updated LibGroupInSpecT
