### ISSUE TITLE
Missing gems/enchants doesn't work

### ISSUE THREAD

**Issue by krofinzki** [BigWigsMods/oRA3#15]
### What steps will reproduce the problem?  
In a raid group using the appropriate Gear checking window the missing gems/enchants will not line up with reality. We tested having items with missing gems and missing enchants, nothing produced different resutlts than the counter being at "0" for anything that was missing.
The item level check seems accurate and working fine however.

### What version of oRA3 are you using?
Tests were made in current version from 2016-09-22 and on the version which was available on 2016-09-20.

### Do you have an error log of what happened?
No

### Please provide any additional information below. (example: localization of your client if not enUS or enGB)
I looked at the code and tried changing
`true, -- INVSLOT_MAINHAND -- 16`
to
`false, -- INVSLOT_MAINHAND -- 16`
... since weapon enchants aren't a thing in this expansion. This did not affect the outcome of the missing gems/enchants check.
I looked more at the code to try to understand how it works. Could this change be the issue?:

> Patch 7.0.3 (2016-07-19): Lone 0's in item strings have been removed so something like ":0:0:0:" has become "::::". 3 new segments have also been added to the end of the item string but their use is unknown at this time.
Source: Bottom of the page on http://wow.gamepedia.com/ItemString

**Comment by funkydude** [comment]
Fixed by https://github.com/BigWigsMods/oRA3/commit/27d5e70f5d425e4766d94320f03ff15b26ce7443
