### ISSUE TITLE
No Oil, Hearty Food or Vantus

### ISSUE THREAD

**Issue by TheDescender** [BigWigsMods/oRA3#151]
## Describe the problem
Doesn't track oils, doesn't track hearty food, doesn't track lower tier vantus, but does lower tier flasks. How is this addon in its current state useful?

### What steps will reproduce the problem?

1.  Open your pane with all these buffs on and you'll see :)

### Consider attaching a screenshot below to help describe your issue (Attach directly, do not link to other websites)

![image](https://github.com/user-attachments/assets/fb8b6d98-9a6c-4564-9f07-3145622906a8)

### What version of the addon are you using? (Stating 'latest' is not useful)
V11.0.3

### Do you have an error log of what happened?
Nope

**Comment by TreizeEU** [comment]
I noticed during last night's raid, that Vantus Runes haven't been updated for Nerub-ar Palace bosses (they're all still Dragonflight raid boss ID's, as of addon version 11.0.4, line 41 of file oRA3/Modules/Consumables.lua).

**Comment by funkydude** [comment]
Oil has never been in and likely never will be as it would need every player to use the addon. Others should be fixed.
