### ISSUE TITLE
Last Stand showing wrong CD

### ISSUE THREAD

**Issue by shinnova** [BigWigsMods/oRA3#18]
### What steps will reproduce the problem?  
1.  Track warrior's Last Stand ability
2.  Have a warrior use Last Stand
3.  See a CD of 90 seconds instead of the 180 seconds CD it actually has

### What version of oRA3 are you using?
v7.1.0

### Do you have an error log of what happened?
Not applicable

**Comment by oleerik** [comment]
Wouldn't updating https://github.com/BigWigsMods/oRA3/blob/master/modules/Cooldowns/Cooldowns.lua be enough? I can PR it if that's correct

**Comment by nebularg** [comment]
Don't think there are any mods for it, must have missed updating that
