### ISSUE TITLE
Variable Cooldowns

### ISSUE THREAD

**Issue by G3sch4n** [BigWigsMods/oRA3#19]
Currently there are some legendarys and talents that augement the cooldown of certain skills.
An example would be the ring for protection warrior ,the bracers for disciplin priest or the talent for tranquility for resto druids.
Since tracking those would be a complete nightmare and next to impossible my suggestion would be to use a third color for cd possibly ready.
So basically the cooldown bar for those skills would be split into two colors.
When the first part of the bar has vanished the cooldown is ready if the skill is augmented.
Especially for the ring and the bracers this kind of system would help a lot since they are more or less unpredicatable by normal means.

**Comment by Gnarfoz** [comment]
Also, protection paladin artifact trait: http://www.wowhead.com/spell=209376/forbearant-faithful
