### ISSUE TITLE
Version Check

### ISSUE THREAD

**Issue by Stanzilla** [BigWigsMods/oRA3#2]
What is the enhancement in mind? How should it look and feel?

Please add a version check so I know if my raiders have oRA3 installed or not without manually comparing the list of armor durability/etc with the list of raiders.

Thanks!

Please provide any additional information below.

**Comment by funkydude** [comment]
The main problem is now resolved by https://github.com/BigWigsMods/oRA3/commit/45099a78bb15fe33b6604d85343b196f3fdb468b without needing an actual version check.
