### ISSUE TITLE
oRA3 error on completing Broken Isles World Quest via the map using Paladin Silver Hand Orders

### ISSUE THREAD

**Issue by holypally2** [BigWigsMods/oRA3#21]
### What steps will reproduce the problem?  
1.  Open Broken Isles Map
2.  Click on "Silver Hand Orders" then click on the quest to complete.
3.  Blizzard Error comes up with option to disable oRA3 and the quest disappears from the map without completing. Closing and reopening the map will refresh and quest will show as available again. You have to disable oRA3 to be able to complete the Silver Hand Orders and the chosen quest.

### What version of oRA3 are you using?
oRA3-v7.1.2.

### Do you have an error log of what happened?

I do not have an error log or a screenshot. I can try to get one for you, What bug mods are you using?
This happened earlier this month with DBM Core, but stopped when DBM was updated. Now it seems oRA3 is triggering the error.

### Please provide any additional information below. (example: localization of your client if not enUS or enGB)

I run the latest release versions of oRA3, DBM mods, Skada, VuhDo, Greenwall and Incognito.

Full UI reset and reconfiguration of all addons November 27, 2016. To clear out issues with AdvancedInterfaceOptions  and other mods I am no longer using. 

US Realm Farstriders/SilverHand/ThoriumBrotherhood

Mac Pro 5,1, Quad-Core Intel Xeon,  ATI Radeon HD 5870
32 GB RAM
MacOS X Yosemite 10.10.5

**Comment by nebularg** [comment]
This isn't caused by oRA (or DBM, or any other addon that will eventually be blamed), it's from taint spreading to that map button from going into combat with your map open. Just reload your UI and try again.

**Comment by holypally2** [comment]
I was NOT in combat. In one instance I was in my class hall. 

The error message from Blizzard said it was oRA3.

**Comment by nebularg** [comment]
It happens at some point AFTER you've been in combat with your map open. I can assure you oRA does nothing related to the map, so there is no code I can change to fix this. It gets blamed because it is the last addon to use a [tainted code path](http://wow.gamepedia.com/Secure_Execution_and_Tainting#Secure_execution_and_.22Tainting.22). Like I said, simply reload your UI (or relog) and try again.
