### ISSUE TITLE
Bug together with BigWIgs in raids

### ISSUE THREAD

**Issue by trininja2k** [BigWigsMods/oRA3#27]
### What steps will reproduce the problem?  
1.  Run oRA3 and BigWigs in raids.
2.  
3.  

### What version of oRA3 are you using?
Latest from Curse: 7.2.2

### Do you have an error log of what happened?
```
1890x oRA3\modules\Cooldowns\Registry.lua:316: <unnamed>:SetPoint(): <unnamed> is dependent on this
[C]:: in function 'SetPoint'
oRA3\modules\Cooldowns\Registry.lua:316: in function 'BarStopped'
...face\oRA3\modules\Cooldowns\Displays\Bars.lua:54: in function '?'
...ler\Libs\CallbackHandler-1.0\CallbackHandler-1.0-6.lua:145: in function <...ler\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:145>
[string "safecall Dispatcher[2]"]:4: in function <[string "safecall Dispatcher[2]"]:4>
[C]:: ?
[string "safecall Dispatcher[2]"]:13: in function '?'
...ler\Libs\CallbackHandler-1.0\CallbackHandler-1.0-6.lua:90: in function 'Fire'
...oRA3\libs\LibCandyBar-3.0\LibCandyBar-3.0-93.lua:326: in function 'Stop'
...oRA3\libs\LibCandyBar-3.0\LibCandyBar-3.0-93.lua:68: in function <...oRA3\libs\LibCandyBar-3.0\LibCandyBar-3.0.lua:64>
```

### Please provide any additional information below. (example: localization of your client if not enUS or enGB)
I can't really tell what is happening, I just setup oRA3 and BigWigs together and very often in Raids the bars are jumping into the BigWigs bars list and only wen't back when the cooldown is finished.

**Comment by funkydude** [comment]
Update to v7.2.4 and re-open if it happens again.
