### ISSUE TITLE
Provide the BattleRes information in a LDB display

### ISSUE THREAD

**Issue by Stanzilla** [BigWigsMods/oRA3#3]
What is the enhancement in mind? How should it look and feel?
It would be great if we could optionally get the battle res count and remaining time in a LDB display instead of a seperate frame.
I'd suggest a short text that doesn't need any descriptions, something like "2 (3:05)" for 2 current availables resses and 3:05 min until the next one.

Please provide any additional information below.
If you don't want LDB in oRA3, could you please add a public API for those values so that a small LDB display addon can reuse the logic from oRA3?

**Comment by nebularg** [comment]
finally updated [Broker_BattleRes](https://www.curseforge.com/wow/addons/broker_battleres) so I'm just gonna close this
