### ISSUE TITLE
v7.2.5 inital install error

### ISSUE THREAD

**Issue by ceylina** [BigWigsMods/oRA3#30]
### What steps will reproduce the problem?  
1.  Fresh install of version 
2.  log in to character
3.  error pops up

### What version of oRA3 are you using?
v7.2.5

### Do you have an error log of what happened?
1x oRA3\modules\Cooldowns\Cooldowns.lua:1367: attempt to index global 'self' (a nil value)
oRA3\modules\Cooldowns\Cooldowns.lua:1367: in function <oRA3\modules\Cooldowns\Cooldowns.lua:1329>
oRA3\modules\Cooldowns\Cooldowns.lua:1395: in function `OnProfileUpdate'
oRA3\modules\Cooldowns\Cooldowns.lua:1514: in function `OnRegister'
oRA3\modulePrototype.lua:7: in function <oRA3\modulePrototype.lua:5>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[1]"]:9: in function <[string "safecall Dispatcher[1]"]:5>
(tail call): ?
...\AngryAssignments\libs\AceAddon-3.0\AceAddon-3.0-12.lua:529: in function `InitializeAddon'
...\AngryAssignments\libs\AceAddon-3.0\AceAddon-3.0-12.lua:644: in function <...\AngryAssignments\libs\AceAddon-3.0\AceAddon-3.0.lua:636>

Locals:
nil

### Please provide any additional information below. (example: localization of your client if not enUS or enGB)

this is upon initial install of the addon

**Comment by nebularg** [comment]
Thanks, missed that when I was refactoring
