### ISSUE TITLE
Cooldowns: Add racial abilities

### ISSUE THREAD

**Issue by ekto-illidan** [BigWigsMods/oRA3#38]
I use oRA cooldown windows to track interrupts and a few other abilities in mythic plus. It would be hugely beneficial if we could track racial certain racial abilities.

Note that some racials have multiple spell IDs for different classes. This shouldn't matter in the context of oRA cooldown tracking. All racials are available at level 1.

**Comment by nebularg** [comment]
I started on this some time ago, I suppose I could finish it 😒 It ended up being more involved than I thought because Blood Fury and Arcane Torrent that have spell ids that are shared between multiple classes, which doesn't work so well with how the spell look ups are coded currently.

**Comment by ekto-illidan** [comment]
Do you have a working branch I could contribute on?

**Comment by nebularg** [comment]
I was doing some convoluted shit before, lol, ended up being pretty straight forward

**Comment by ekto-illidan** [comment]
Nice! Thanks a bunch, much appreciated 👍
