### ISSUE TITLE
Bar Icons Disappearing

### ISSUE THREAD

**Issue by swinu** [BigWigsMods/oRA3#40]
ElvUI Style Bars with Icon Enabled

The icon is disappearing or coming up blank testing with ORA3 on its own and still getting the issue

Latest v7.3.6

No Errors being produced

Haven't found exactly what might be causing it, did a reinstall of addon and even cleared cache to no avail, this didn't happen on previous version that I saw.

![](https://i.imgur.com/UDYbPyi.png)

**Comment by funkydude** [comment]
Seems to be working fine here, cannot reproduce. Try with only oRA enabled.

**Comment by swinu** [comment]
I have found using "Hide out of range" filter is a temporary work around. It seems it has to do with the status and it self updating.

**Comment by nebularg** [comment]
If you revert back to v7.3.4 does the issue go away?

**Comment by swinu** [comment]
v7.3.4 is showing no icons at all even with out of range filter which fixed  v7.3.6 however default still shows icons and TukUI works perfectly
https://i.imgur.com/q4fcPJU.png

And I don't think it is at all, this is what happens mid encounter and have found its usually triggered by a status effect
https://i.imgur.com/OAr91q1.png

I have missed however that it doesn't seem like TukUI style is being effected with this issue

**Comment by nebularg** [comment]
Try [v7.3.6-1-g94e6a36](https://wow.curseforge.com/projects/ora3/files/2549525/download) (it has an updated bar lib that should fix the icon issue)
