### ISSUE TITLE
New Priest CDs

### ISSUE THREAD

**Issue by Tianaryl** [BigWigsMods/oRA3#44]
Please add new priest CDs to CD tracker

### What steps will reproduce the problem?  
1.  Holy priest CD: Power Word: Salvation (spell ID 265202)
2.  Disc priest CD: Luminous Barrier (spell ID 271466)
3.  

### What version of oRA3 are you using?
8.0.0

### Do you have an error log of what happened?
n/a

**Comment by nebularg** [comment]
Added in c8007ce6dce509581f8777dc36d374a3639c2363
