### ISSUE TITLE
Resurection Monitor not working in LFR

### ISSUE THREAD

**Issue by Scaver** [BigWigsMods/oRA3#45]
### What steps will reproduce the problem?  
1.  Go to LFR
2.  In Boss Fight someone has to die
3.  Resurection Timer only show "0    0:00"

### What version of oRA3 are you using?
v 8.0.0

### Do you have an error log of what happened?
No

### Please provide any additional information below. (example: localization of your client if not enUS or enGB)
Localization DEde (Germany)

**Comment by funkydude** [comment]
The resurrection system is no longer active in LFR so it's not a bug.
