### ISSUE TITLE
Not showing Cooldowns

### ISSUE THREAD

**Issue by Mythagos** [BigWigsMods/oRA3#46]
### What steps will reproduce the problem?  
1.  Hi, Thanks for a great addon that I've been using for many years!
However I cannot seem to get the Cooldown Window to show.
I can do a TEST and then it will show but wont open in normal situation.
2.  Also, as another person has the same issue, I cannot see the 2 new Priest Cooldowns ;-(
3.  

### Do you have an error log of what happened?

Cannot seem to find any error report Im afraid ;-/

**Comment by nebularg** [comment]
If the window is locked you won't see it (if that is what you're saying). I just updated the cooldowns so post back if you're still having a problem
