### ISSUE TITLE
Invite by Message

### ISSUE THREAD

**Issue by TheDevilofme** [BigWigsMods/oRA3#51]
### The Idea
Invite members when the keyword is in a msg and not only when its the whole message

### The Code that needs to be edited
Actually theres a comparision in Invite.lua in the function checkKeywords it would be possible to replace it with string.find(msg, keyword) or with string.match, when match is used it would be possible to use regex which would be much more flexible than now (I don't know lua well maybe it isn't possible, but it would be very nice)

**Comment by funkydude** [comment]
No plans for this.
