### ISSUE TITLE
No way to get a list of raiders versions of ORA3.

### ISSUE THREAD

**Issue by greenstones** [BigWigsMods/oRA3#55]
### What steps will reproduce the problem?  
1.  Unable to see current version of ora3 for everyone in the raid.
2.  No command listed.
3.  No error.

### What version of oRA3 are you using?
8.0.2 as downloaded.

### Do you have an error log of what happened?
No

### Please provide any additional information below. (example: localization of your client if not enUS or enGB)
Would like a simple /ora3 version
or /ravers to see the version of the ora3 that everyone has in the raid.

**Comment by funkydude** [comment]
I don't see a big need for this.
