### ISSUE TITLE
Addon has been blocked from action...

### ISSUE THREAD

**Issue by YammYcoding** [BigWigsMods/oRA3#64]
### What steps will reproduce the problem?  
1.  Install addon
2.  Open wow
3.  Error onload - wow asks to block oRA3 due to "Addon has been blocked from action..."

### What version of oRA3 are you using?
last ## Version: v8.0.7

### Do you have an error log of what happened?
no, wow just asked to block the addon :(

### Please provide any additional information below. (example: localization of your client if not enUS or enGB)
client enUS.

I saw some forum posts about it, looks like some functions got recently blocked by blizz.

https://us.battle.net/forums/en/wow/topic/20759240920

**Comment by funkydude** [comment]
Does this happen if you disable all addons and leave oRA3 enabled?

**Comment by funkydude** [comment]
No response, closing.
