### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by Addonman** [BigWigsMods/oRA3#67]
### What steps will reproduce the problem?  
1.  open addon for azerite -azerte forge+azerite power weights
2.  
3.  

### What version of oRA3 are you using?
last available v8.2.3

### Do you have an error log of what happened?

yes
Message: ..\AddOns\oRA3\libs\AceGUI-3.0\AceGUI-3.0.lua line 643:
   Action[SetPoint] failed because[SetPoint would result in anchor family connection]: attempted from: <unnamed>:SetAllPoints.
Debug:
   (tail call): ?
   [C]: SetAllPoints()
   oRA3\libs\AceGUI-3.0\AceGUI-3.0.lua:643:
      oRA3\libs\AceGUI-3.0\AceGUI-3.0.lua:639
   [C]: ?
   oRA3\libs\AceGUI-3.0\AceGUI-3.0.lua:72:
      oRA3\libs\AceGUI-3.0\AceGUI-3.0.lua:70
   oRA3\libs\AceGUI-3.0\AceGUI-3.0.lua:409: PerformLayout()
   oRA3\libs\AceGUI-3.0\AceGUI-3.0.lua:414: DoLayout()
   oRA3\libs\AceGUI-3.0\AceGUI-3.0.lua:484:
      oRA3\libs\AceGUI-3.0\AceGUI-3.0.lua:480
   [C]: GetWidth()
   oRA3\libs\AceGUI-3.0\AceGUI-3.0.lua:641:
      oRA3\libs\AceGUI-3.0\AceGUI-3.0.lua:639
   [C]: ?
   oRA3\libs\AceGUI-3.0\AceGUI-3.0.lua:72:
      oRA3\libs\AceGUI-3.0\AceGUI-3.0.lua:70
   oRA3\libs\AceGUI-3.0\AceGUI-3.0.lua:409: PerformLayout()
   oRA3\libs\AceGUI-3.0\AceGUI-3.0.lua:414: DoLayout()
   oRA3\libs\AceGUI-3.0\AceGUI-3.0.lua:435: AddChild()
   AzeriteForge\Utilities\Frames.lua:785: Balls()
   AzeriteForge\AzeriteForge.lua:903:
      AzeriteForge\AzeriteForge.lua:903
   [C]: Show()
   ..\FrameXML\InterfaceOptionsFrame.lua:28: InterfaceOptionsList_DisplayPanel()
   ..\FrameXML\InterfaceOptionsFrame.lua:46: InterfaceOptionsListButton_OnClick()
   [string "*:OnClick"]:2:
### Please provide any additional information below. (example: localization of your client if not enUS or enGB)
+ not detecing F.E.A.S.T feast

**Comment by nebularg** [comment]
Added the 8.2 feast and cauldron in d914a1f, gonna close this since the AceGUI error is unrelated to oRA3
