### ISSUE TITLE
Battle ress timer bugs in mythic plus

### ISSUE THREAD

**Issue by Pellew** [BigWigsMods/oRA3#84]
### What steps will reproduce the problem?  
1.  Running mythic plus keystones
2.  
3.  

### What version of oRA3 are you using?
Ora3-v8.3.1zip

### Do you have an error log of what happened?
I got this one, but not sure if it the one that makes the issue:

Message: Interface\AddOns\oRA3\libs\AceGUI-3.0\AceGUI-3.0.lua:723: Action[SetPoint] failed because[SetPoint would result in anchor family connection]: attempted from: <unnamed>:SetPoint.
Time: Sun Jul 12 20:41:11 2020
Count: 1
Stack: Interface\AddOns\oRA3\libs\AceGUI-3.0\AceGUI-3.0.lua:723: Action[SetPoint] failed because[SetPoint would result in anchor family connection]: attempted from: <unnamed>:SetPoint.
[string "=(tail call)"]: ?
[string "=[C]"]: in function SetPoint'
[string "@Interface\AddOns\oRA3\libs\AceGUI-3.0\AceGUI-3.0.lua"]:723: in function <Interface\AddOns\oRA3\libs\AceGUI-3.0\AceGUI-3.0.lua:681>
[string "=[C]"]: ?
[string "@Interface\AddOns\oRA3\libs\AceGUI-3.0\AceGUI-3.0.lua"]:72: in function <Interface\AddOns\oRA3\libs\AceGUI-3.0\AceGUI-3.0.lua:70>
[string "@Interface\AddOns\oRA3\libs\AceGUI-3.0\AceGUI-3.0.lua"]:432: in function PerformLayout'
[string "@Interface\AddOns\oRA3\libs\AceGUI-3.0\AceGUI-3.0.lua"]:437: in function DoLayout'
[string "@Interface\AddOns\oRA3\libs\AceGUI-3.0\AceGUI-3.0.lua"]:458: in function AddChild'
[string "@Interface\AddOns\ElvUI_OptionsUI\Libraries\Ace3\AceConfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua"]:1849: in function FeedGroup'
[string "@Interface\AddOns\ElvUI_OptionsUI\Libraries\Ace3\AceConfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua"]:2028: in function Open'
[string "@Interface\AddOns\ElvUI\Core\Config.lua"]:848: in function `Config_OpenWindow'
[string "@Interface\AddOns\ElvUI\Core\Config.lua"]:309: in function <Interface\AddOns\ElvUI\Core\Config.lua:302>

Locals: <none>

### Please provide any additional information below. (example: localization of your client if not enUS or enGB)
I have tried with a no other addons install besides Ora3, still the same.
Tried with a fresh WTF and Interface folders
Tried with uninstall wow, and newly install the game.
Tried unstall windows 10, and start all over again.

When i install the addon in a fresh WTF and Interface folder, i still see some profiles to choose when i open the addon.
The profiles i see is:
Default
Doomhammer
Pellem-Doomhammer
Warrior.

When i try to delete these profiles from the ingame dropdown menu i cant select any.

Hope you guys can help me.

Thx in advance

**Comment by nebularg** [comment]
I'm not sure what the issue with the res timer is? That stack trace looks like an error originating in ElvUI when opening their config?

**Comment by Pellew** [comment]
Then im not sure what causing my issues. 

My is issues is, whenever i start a mythic plus dungeon, I can’t see the combat ress timer. It simply disappears, and I can’t even toggle it on, because the button becomes unclickable. As soon as the m+ dungeon is over, and I leave the instance, I can see the timer, and the button works again to toggle the timer on and off

Mayby if have an idea or heard of something similar before ??

**Comment by nebularg** [comment]
It only shows in the dungeon if you have a class that can battle res, showing outside a dungeon is so you can position it

**Comment by Pellew** [comment]
Okay, so just to clarify a bit.

If I’m not the class who has the battle ress, but having a Druid in the group, will it show then ?

Should it be showing if we have none classes with battle ress, but having two hunters with engineer ress ?

Thx in advance

Mvh
Jesper Obitsø Nielsen
________________________________
Fra: Kyle Buller <notifications@github.com>
Sendt: Monday, July 20, 2020 7:09:59 PM
Til: BigWigsMods/oRA3 <oRA3@noreply.github.com>
Cc: Pellew <obitso@hotmail.com>; Author <author@noreply.github.com>
Emne: Re: [BigWigsMods/oRA3] Battle ress timer bugs in mythic plus (#84)


It only shows in the dungeon if you have a class that can battle res, showing outside a dungeon is so you can position it

**Comment by nebularg** [comment]
Yes, I should have said "if your group has a class that can battle res". With Engineers, it will show for just them.

I'll add an option to always show it

**Comment by Pellew** [comment]
Sound good to have the option to always show, since it can be handy as a tank without CR to keep track of the posibility to use CR from engineers

Thx for the response and clarifying, really appreciated since I couldn’t figure out why it sometimes showed, and sometimes where hiding
