### ISSUE TITLE
Error when getting bnet whispers

### ISSUE THREAD

**Issue by yajinni** [BigWigsMods/oRA3#86]
When i get whispers (using WIM so idk if its affects it) Getting this error:
1x oRA3\modules\Invite-Invite.lua:211: attempt to call global 'BNGetNumFriendGameAccounts' (a nil value)
[string "@oRA3\modules\Invite-Invite.lua"]:211: in function <oRA3\modules\Invite.lua:207>
[string "@oRA3\modules\Invite-Invite.lua"]:247: in function `v'
[string "@oRA3\oRA3-v9.0.1.lua"]:237: in function <oRA3\oRA3.lua:234>

Locals:
bnetIDAccount = 157
friendIndex = 29
(*temporary) = 1
(*temporary) = nil
(*temporary) = 29
(*temporary) = "attempt to call global 'BNGetNumFriendGameAccounts' (a nil value)"
playerFaction = "Alliance"
playerRealm = "Moon Guard"

**Comment by madar2252** [comment]
getting the same without WIM
