### ISSUE TITLE
Missing classes for cooldown tracking

### ISSUE THREAD

**Issue by Faraom** [BigWigsMods/oRA3#88]
Im trying to select the cooldowns I want to be able to track from every class, but some classes (DK, Hunter, Monk, Paladin, Priest) have no spell in the CD tab, so I cant select any checkbox; The other classes work fine and all their CD's are present in the list.

### What steps will reproduce the problem?  
1.  /Racd
2.  cooldown tab
3.  in settings select any of these classes: DK, Hunter, Monk, Paladin, Priest

### What version of oRA3 are you using?
v9.0.3 

### Do you have an error log of what happened?
No

### Please provide any additional information below. (example: localization of your client if not enUS or enGB)
![Ora3 issue](https://user-images.githubusercontent.com/73147673/96528086-64ea8080-1247-11eb-8c8d-7b508b16214a.PNG)

**Comment by nebularg** [comment]
Finally finished with updating cooldowns, so this is fixed

**Comment by Faraom** [comment]
Awesome, indeed all the classes are showing now, but I realized that "Anti-magic Zone" is missing from the DK's cooldowns, may be missing other spells, but thats the one I realized as missing for now.
![Ora3 AMZ missing](https://user-images.githubusercontent.com/73147673/96807229-add33e00-13db-11eb-854e-eb362b4a46ed.PNG)

**Comment by Shenzory** [comment]
Message: ...nterface\AddOns\oRA3\modules\Cooldowns\Cooldowns.lua:95: attempt to compare table with number
Time: Thu Oct 22 10:34:16 2020
Count: 1
Stack: ...nterface\AddOns\oRA3\modules\Cooldowns\Cooldowns.lua:95: attempt to compare table with number
[string "=(tail call)"]: ?
[string "@Interface\AddOns\oRA3\modules\Cooldowns\Cooldowns.lua"]:95: in function `IsSpellUsable'
[string "@Interface\AddOns\oRA3\modules\Cooldowns\Cooldowns.lua"]:174: in function <...nterface\AddOns\oRA3\modules\Cooldowns\Cooldowns.lua:171>
[string "@Interface\AddOns\oRA3\modules\Cooldowns\Cooldowns.lua"]:200: in function <...nterface\AddOns\oRA3\modules\Cooldowns\Cooldowns.lua:196>
[string "@Interface\AddOns\oRA3\modules\Cooldowns\Cooldowns.lua"]:1277: in function `?'
[string "@Interface\AddOns\ElvUI\Libraries\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:119: in function <...ies\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@Interface\AddOns\ElvUI\Libraries\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:29: in function <...ies\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@Interface\AddOns\ElvUI\Libraries\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:64: in function `Fire'
[string "@Interface\AddOns\oRA3\oRA3.lua"]:456: in function `?'
[string "@Interface\AddOns\ElvUI\Libraries\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:119: in function <...ies\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@Interface\AddOns\ElvUI\Libraries\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:29: in function <...ies\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@Interface\AddOns\ElvUI\Libraries\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:64: in function `Fire'
[string "@Interface\AddOns\oRA3\libs\LibGroupInSpecT-1.1\LibGroupInSpecT-1.1.lua"]:864: in function `eventhandler'
[string "@Interface\AddOns\oRA3\libs\LibGroupInSpecT-1.1\LibGroupInSpecT-1.1.lua"]:129: in function <...RA3\libs\LibGroupInSpecT-1.1\LibGroupInSpecT-1.1.lua:127>

Locals: <none>

How fix this?

**Comment by nebularg** [comment]
They error was fixed in 88856b77a8ea97cbb34fa0b82aa0eac00162161f and I also fixed a few other data problems (including Anti-Magic Zone) in 60a09dbc3cadc4788cab557160e7c545dacd3a79.

Any other missing/inaccurate spell info is useful, thanks!
