### ISSUE TITLE
Bnet whispers from classic wow

### ISSUE THREAD

**Issue by yajinni** [BigWigsMods/oRA3#89]
When i get whispers from people playing classic wow i get this error:
3x oRA3\modules\Invite-Invite.lua:218: attempt to index local 'realmName' (a nil value)
[string "@oRA3\modules\Invite-Invite.lua"]:218: in function <oRA3\modules\Invite.lua:207>
[string "@oRA3\modules\Invite-Invite.lua"]:249: in function `v'
[string "@oRA3\oRA3-v9.0.3.lua"]:237: in function <oRA3\oRA3.lua:234>

Locals:
bnetIDAccount = 103
friendIndex = 20
accountInfo = <table> {
 isFriend = true
 isDND = false
 isFavorite = false
 gameAccountInfo = <table> {
 }
 accountName = "|Kq34|k"
 battleTag = "Juicyapple#1593"
 note = ""
 rafLinkType = 0
 bnetAccountID = 103
 appearOffline = false
 customMessage = "so i lied. i did not nap"
 lastOnlineTime = 1603164732
 customMessageTime = 1602470716
 isAFK = false
 isBattleTagFriend = true
}
(for index) = 1
(for limit) = 3
(for step) = 1
i = 1
info = <table> {
 isGameAFK = false
 clientProgram = "WoW"
 characterName = "Juicyapple"
 isGameBusy = false
 factionName = "Alliance"
 playerGuid = "Player-4387-02792124"
 wowProjectID = 2
 gameAccountID = 425
 realmID = 4387
 hasFocus = true
 canSummon = false
 isWowMobile = false
 areaName = "Dun Morogh"
 className = "Warrior"
 richPresence = "WoW Classic - Ashkandi"
 characterLevel = 1
 raceName = "Gnome"
 isOnline = true
}
charName = "Juicyapple"
realmName = nil
(*temporary) = "Moon Guard"
(*temporary) = nil
(*temporary) = true
(*temporary) = nil
(*temporary) = "attempt to index local 'realmName' (a nil value)"
playerFaction = "Alliance"
playerRealm = "Moon Guard"

**Comment by nebularg** [comment]
Thanks
