### ISSUE TITLE
Warnings on WoW Start (Invalid Spell ID)

### ISSUE THREAD

**Issue by Potsrabe** [BigWigsMods/oRA3#90]
Hello,
if I start wow on german client I get this warnings:

oRA3: Invalid spell id 130736
oRA3: Invalid spell id 267798
oRA3: Invalid spell id 204150
oRA3: Invalid spell id 204035
oRA3: Invalid spell id 280711
oRA3: Invalid spell id 198664
oRA3: Invalid spell id 193526

**Comment by nebularg** [comment]
Fixed now
