### ISSUE TITLE
Error on Entering/Leaving Horrific Vision on BM Hunter

### ISSUE THREAD

**Issue by Tequima** [BigWigsMods/oRA3#91]
### What steps will reproduce the problem?  
1.  Enter Horrific Vision (of Ogrimmar) 
2.  or Leave Horrific Vision

### What version of oRA3 are you using?
v9.0.4

### Do you have an error log of what happened?
14x oRA3\modules\Cooldowns\Cooldowns.lua:95: attempt to compare table with number
[string "@oRA3\modules\Cooldowns\Cooldowns.lua"]:95: in function `IsSpellUsable'
[string "@oRA3\modules\Cooldowns\Cooldowns.lua"]:174: in function <oRA3\modules\Cooldowns\Cooldowns.lua:171>
[string "@oRA3\modules\Cooldowns\Cooldowns.lua"]:200: in function <oRA3\modules\Cooldowns\Cooldowns.lua:196>
[string "@oRA3\modules\Cooldowns\Cooldowns.lua"]:1277: in function `?'
[string "@DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:119: in function <...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:29: in function <...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:64: in function `Fire'
[string "@oRA3\oRA3-v9.0.4.lua"]:456: in function `?'
[string "@DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:119: in function <...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:29: in function <...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:64: in function `Fire'
[string "@oRA3\libs\LibGroupInSpecT-1.1\LibGroupInSpecT-1.1-92.lua"]:426: in function `Query'
[string "@oRA3\libs\LibGroupInSpecT-1.1\LibGroupInSpecT-1.1-92.lua"]:688: in function `DoPlayerUpdate'
[string "@oRA3\libs\LibGroupInSpecT-1.1\LibGroupInSpecT-1.1-92.lua"]:842: in function `eventhandler'
[string "@oRA3\libs\LibGroupInSpecT-1.1\LibGroupInSpecT-1.1-92.lua"]:129: in function <...RA3\libs\LibGroupInSpecT-1.1\LibGroupInSpecT-1.1.lua:127>

### Please provide any additional information below. (example: localization of your client if not enUS or enGB)
Solo with 2 pets, one Ferocity Spirit Beast +

**Comment by nebularg** [comment]
Fixed in 88856b77a8ea97cbb34fa0b82aa0eac00162161f, thanks
